INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN2CF852A1Y4WD', 'Rebeccaton Branch', 'Gonzalezburgh', 'USA', 'William Coleman');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNA4J7NSYYAAAN', 'South Megan Branch', 'Obrienfort', 'USA', 'Joseph Jones');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN1W4449M6V92Z', 'Smithberg Branch', 'Lake Barbarahaven', 'USA', 'Patricia Castaneda');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNJVSZ46YB03LS', 'New Paul Branch', 'North Kyle', 'USA', 'James Webb');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN85W9PR4G0EBU', 'Lake Susan Branch', 'Richardbury', 'USA', 'David Chen');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNO78ZZDGH8403', 'Duffyport Branch', 'Patelfurt', 'USA', 'Brenda Cross');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN44YB25YDJSQQ', 'North Haley Branch', 'Amandaville', 'USA', 'Michele Johnson');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNHYW9VFNRKC14', 'Georgemouth Branch', 'Vickishire', 'USA', 'Rachel Heath');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN2LHHCC0NFIKJ', 'Floresside Branch', 'Armstrongshire', 'USA', 'Alec Wade');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNAD5NYRQ7NATS', 'Jeffreybury Branch', 'Lake Jasonshire', 'USA', 'Karen Barnett');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNCJ2BXPICJLTX', 'Richardshire Branch', 'Alanfort', 'USA', 'Louis Huff');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNTQA9ANZ1D2RO', 'New Tammy Branch', 'East Christophermouth', 'USA', 'Michael Arellano');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNCC0R5W9QP7R8', 'Carterland Branch', 'South Jenniferchester', 'USA', NULL);
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNK439ZTW1CZP1', 'East Rodney Branch', 'West Jamesfurt', 'USA', 'Samantha Walter');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNHGJBPTM2Z0J0', 'South Jacob Branch', 'West Robertstad', 'USA', 'Mario Murray');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNNBGSBKI5A44R', 'New Justin Branch', 'Robinsonville', 'USA', 'Karen Gonzalez');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNNP3YCIBRH8XJ', 'Jonathanton Branch', 'Lake Ryanstad', 'USA', 'Jessica Martin');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN5GOZX249MJ1W', 'Floresshire Branch', 'South Vickie', 'USA', 'Emily Wilson');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNG0UQFFLQ7QA8', 'Lake Jesse Branch', 'Arnoldbury', 'USA', 'Julie Roth');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN9FG0SAAXP2IZ', 'North Brent Branch', 'Stephaniestad', 'USA', 'James Clark');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN2N7JD3OQW3SE', 'Paulfort Branch', 'East Samantha', 'USA', 'Michael Brewer');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNJT8VH85LUSRI', 'East Oscar Branch', 'Valdezshire', 'USA', 'Dr. Mary Jackson DVM');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNGOENYZHEKRWU', 'Caseystad Branch', 'Angelaton', 'USA', 'Sharon Jones');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNV54ASL3I46C8', 'New Ashley Branch', 'West Anne', 'USA', 'Roger Haney');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNBDE04FEMV17R', 'Lake Christopherfurt Branch', 'Wilcoxstad', 'USA', 'Kendra Michael');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN7ZYCXS4K7FS7', 'Mataville Branch', 'New Robertborough', 'USA', 'Victor Thompson');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNHSLGNV61UV05', 'Petersonberg Branch', 'New Matthewville', 'USA', 'Stacy Harris');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNO6GMCCX0ZJ96', 'West Melissaport Branch', 'Andrewmouth', 'USA', 'Susan Wilson');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN9LN6O1S6Y0QY', 'New Susan Branch', 'Sextonmouth', 'USA', 'William Mcgee');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN4NRTWM933H2M', 'Jacobshire Branch', 'Port Tracy', 'USA', 'David Davis');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNX54IPHXK2LU4', 'East Carolmouth Branch', 'North Katherineborough', 'USA', NULL);
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNTF4TBK7BKW5G', 'East Rachel Branch', 'New Thomas', 'USA', 'Thomas Davis');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNW89PM21S06HF', 'Evansstad Branch', 'Nicholasfurt', 'USA', 'Megan Jennings');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN1OPVWTRGERWZ', 'New Jennifertown Branch', 'Rebeccabury', 'USA', 'Michele Walker');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNRWX224T5D1EA', 'Port Sherryland Branch', 'East Ricardo', 'USA', 'Mark Winters');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNWQXXVG8OUJI9', 'South Marcland Branch', 'New Krystal', 'USA', 'Eric Lozano');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNVRXQEOMC3LCS', 'Dudleyview Branch', 'Port Daniellemouth', 'USA', 'Kristina Smith');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRND7ZVVLQZNRN6', 'Mortonberg Branch', 'North Cynthia', 'USA', 'Kelly Alvarez');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN52766B0OS7HG', 'Allenberg Branch', 'Rickyborough', 'USA', 'Nicole Bell');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNV0V06N1TCG3E', 'North Nicolemouth Branch', 'Hollowaystad', 'USA', 'Amy Hart');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNGU1JGTYBYWPB', 'New Cynthia Branch', 'Alvaradotown', 'USA', 'Brenda Cohen');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNQMXNMPXVV8CR', 'New Robertmouth Branch', 'New Vanessamouth', 'USA', 'Sarah Roberts');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNA7NSZ5I3T189', 'Josephbury Branch', 'Bethland', 'USA', 'Amanda King');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN6547YMKQ5A6D', 'North Stephanie Branch', 'North Katrinashire', 'USA', 'Denise Duarte');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNF618SVNJVZBN', 'Lake Scottburgh Branch', 'Jacksonchester', 'USA', 'Miss Mary Nguyen MD');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNV1ELQGL1LT61', 'Marshallfort Branch', 'Barnesmouth', 'USA', 'Courtney Hanson');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNCXC2RE4J3E3N', 'Davisland Branch', 'Rubioton', 'USA', 'Jacqueline Braun');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNWG0ZBMIQWLJM', 'Brooksbury Branch', 'West Mary', 'USA', 'Carla Yates');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN9EFY7ZKSRMPG', 'East Rachel Branch', 'South William', 'USA', 'Thomas Carr');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNM2207NENICOV', 'North Daniel Branch', 'Stephenchester', 'USA', 'Lori Mckee PhD');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNBNM8QRVPFYJQ', 'Angelabury Branch', 'Lake Karen', 'USA', 'Nicole Brown');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNP6KOI5Y870QS', 'Jonesborough Branch', 'North Paulstad', 'USA', 'Kristin Russell');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNIYMH2IWACOFQ', 'Deckerhaven Branch', 'North Kelly', 'USA', 'Dr. Michael Edwards DDS');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNRLBUU4FH726K', 'North Maria Branch', 'Thompsonchester', 'USA', 'Amanda Martinez');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNVJIYHNLQKZUW', 'West Kyleside Branch', 'Nancyfurt', 'USA', 'Carlos Robinson');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN6IBLOUTI4K9P', 'Melissashire Branch', 'Lisahaven', 'USA', 'Joseph Jimenez');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNZXJ0BSAQHJ2A', 'New Fredmouth Branch', 'Lake Robert', 'USA', 'Caleb Baker');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNEUQ73NBI44AV', 'Bettybury Branch', 'Jasonport', 'USA', 'David Anderson');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN3T07K69SPIX9', 'Lake John Branch', 'Katherinehaven', 'USA', 'Rachel Hansen');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN5VRNE91950NA', 'Ivantown Branch', 'Brentton', 'USA', 'Ashley Turner');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN1TB9JV48DTYW', 'Collinschester Branch', 'Erikborough', 'USA', 'Carrie Smith');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN01ISWLKMNGXZ', 'Kinghaven Branch', 'West Walterside', 'USA', 'Jay King');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNDS3L9OEGFS65', 'Port Tanyaberg Branch', 'Swansonstad', 'USA', 'Jeff Ingram');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN43LZDH8TQG39', 'Davidfort Branch', 'Bakerstad', 'USA', 'Lauren Cochran');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN3NRZ3IYLRZ9J', 'Kyleville Branch', 'Cobbfort', 'USA', 'Jesus Thomas');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN1HG309K5PUJU', 'Spencerport Branch', 'South Laurenhaven', 'USA', 'Laura Howell');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNJJX0SF3HSCJC', 'Brianshire Branch', 'Beckyburgh', 'USA', 'Loretta Reyes');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNV7NQMF7HFW90', 'Nicholsport Branch', 'West Ninaburgh', 'USA', 'Tina Larson');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNDQB9B21M601D', 'Port Daniel Branch', 'Lake Thomas', 'USA', NULL);
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNPY7AEEV62H2N', 'Karenstad Branch', 'Kennethville', 'USA', 'Gina Booker');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNL8DUGJRR54MS', 'Williamsfurt Branch', 'Katelynview', 'USA', 'Mark Young');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNA9DGCWSEEHT6', 'New Jenniferchester Branch', 'Cookview', 'USA', 'Mrs. Jessica Ponce');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN3MMF37WPVUAN', 'South Annbury Branch', 'Robinsonton', 'USA', 'Christopher Hensley');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNW954CP7D90PG', 'Lindseyfort Branch', 'South Gregory', 'USA', 'Antonio Jackson');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNU8QKQF462SIO', 'South April Branch', 'Palmermouth', 'USA', 'Morgan Mitchell');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNP3T89QZ2EAOK', 'East Andrewborough Branch', 'Ronaldside', 'USA', 'Kelli Bentley');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNV9LZSLHPVID0', 'Port Jamesmouth Branch', 'Gateshaven', 'USA', 'Joshua Hendrix');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNINB6X3QKQ982', 'Lake Alejandro Branch', 'Grantfort', 'USA', 'Maurice Vega');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNKON6DY5S17OX', 'Port April Branch', 'Traciefurt', 'USA', 'Matthew Perkins');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNLFH053V940M8', 'West Christopher Branch', 'New Patriciatown', 'USA', 'Robin Reed');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN0QUM753LFNBO', 'New Kaylaville Branch', 'Debbiebury', 'USA', 'Mr. Eugene Orr II');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNKU3HA0CQJKVX', 'Duncantown Branch', 'Simsfort', 'USA', 'Kimberly Wilson');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNFAMP3OGQT5BA', 'Dawsonside Branch', 'Torresshire', 'USA', 'Bryan Hart');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNWAJ9QZ23SFMB', 'Harveybury Branch', 'Lake Barbara', 'USA', 'Michael Boyd');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNH3UP5OLHCVQ9', 'South Kim Branch', 'South Ronniebury', 'USA', NULL);
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN5P7XNNXP81T1', 'Garciachester Branch', 'Castroport', 'USA', 'Jermaine Archer');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN75I8Q7XWFWLH', 'West Kimberlyton Branch', 'Popehaven', 'USA', 'Shannon Terrell');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNPNFHFJNVER0T', 'Port Alexandraburgh Branch', 'Simonland', 'USA', 'Rebecca Stokes');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNOH5Y2WC7KL10', 'South Samantha Branch', 'South Kevinton', 'USA', 'Andrew Greene');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNWY1QKWKSRY1H', 'West Maria Branch', 'New Jesse', 'USA', 'Megan Hoffman');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNLF7QTZE26GQX', 'Nealport Branch', 'Smithbury', 'USA', 'Timothy Hunter');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNA9O4RK302P7S', 'East Kimberly Branch', 'Popebury', 'USA', 'Elizabeth Cook');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNV9G0K1JSCRAN', 'Stephaniemouth Branch', 'South Kimberly', 'USA', 'Scott Johnson');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN72VVIT7KOXZE', 'East Jennifer Branch', 'Lake Rebecca', 'USA', 'Kyle Wright');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRND99J6TULA8SY', 'New Jessica Branch', 'Michaelstad', 'USA', 'Tammy Shelton');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN0MEEPC4YLGOM', 'South Christopherfort Branch', 'South April', 'USA', 'Brandi Khan');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN0RANDAEZ0A9A', 'Brianamouth Branch', 'Friedmanside', 'USA', 'Amy Edwards');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNQR92A41EW4O7', 'West Johnnyshire Branch', 'Chandlerstad', 'USA', 'James Davenport');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNKU297SF35MI7', 'Blakeburgh Branch', 'New Gary', 'USA', 'Janet Gardner');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNUPXAS3G74XIQ', 'West Katherine Branch', 'Debramouth', 'USA', 'Robert Friedman');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNJC7P52HP2KEW', 'North Miguel Branch', 'Sarahview', 'USA', 'Rebekah Clark');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNAG638LG76D70', 'West Patricia Branch', 'Maciaschester', 'USA', 'Stephen Griffith');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNR2EVJAY9EZKT', 'Juanland Branch', 'Pageview', 'USA', 'Grant Oliver');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN7TM149BVI0GF', 'Lake Joshuaville Branch', 'North Todd', 'USA', 'Robert Moyer');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNKOJQ685ARHV2', 'Tinachester Branch', 'Port Michaelchester', 'USA', 'Olivia Benson');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNPE2NQ86R1U41', 'Randyhaven Branch', 'Mcdonaldfurt', 'USA', 'Kyle Hernandez');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNRE4ERCLXCSMP', 'Mitchellfurt Branch', 'Brianchester', 'USA', 'Dylan Luna');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNM9Q07P6KKFO1', 'Andersonville Branch', 'Port Shannon', 'USA', 'Dana Haynes');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN672Q2S7YLA9G', 'Port Randyfort Branch', 'Williamsstad', 'USA', 'Karen Bernard');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNQSAX539F8RZ7', 'East Anneville Branch', 'North Pedromouth', 'USA', 'Kristen Nunez');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNIPWV0KI7NZHD', 'West Dustinburgh Branch', 'Port Danielborough', 'USA', 'Melissa Holmes');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNH01I3T1ZKGSB', 'Carterberg Branch', 'Monicabury', 'USA', 'Joseph Martinez');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN5JO8HD5HRCQ1', 'Millerville Branch', 'Morrischester', 'USA', 'Jose Martin');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNQS6O3ONQYAI4', 'South Felicia Branch', 'Yatestown', 'USA', 'Troy Wagner');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNXWJ5TKGQZJRH', 'Bradfordberg Branch', 'Carterton', 'USA', 'Sarah Mcbride');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNKCNUPA5PJATD', 'Stevenville Branch', 'West Jessicamouth', 'USA', 'Kevin Garza');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNSXGVBVGQ5CWF', 'Paulmouth Branch', 'Jacobmouth', 'USA', 'Donald Moore');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNB4N4BW4165JB', 'Swansonshire Branch', 'Jonhaven', 'USA', 'Jason Bell');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNFW3VJY37FGW2', 'New Carolynshire Branch', 'Dustinchester', 'USA', 'Andrea Banks');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNPWDCJJWHA9HE', 'Leebury Branch', 'Downsport', 'USA', 'Jessica Silva');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNMWCUE3ETIO41', 'South Brandyburgh Branch', 'North Nicole', 'USA', 'Sheila Ellis');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNUIXX61X9J253', 'West Stephanie Branch', 'Nicolefort', 'USA', 'Justin Sutton');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNIWIOLW67YLLN', 'Hansonberg Branch', 'Whitebury', 'USA', 'John Ross');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNDIOUYP9QNOIO', 'Carlaside Branch', 'Christinamouth', 'USA', 'Amy Allen');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNY07T97G96APO', 'Davistown Branch', 'North Lawrence', 'USA', 'Steven Sutton');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN0C693R41J764', 'South Shannonfurt Branch', 'Lambchester', 'USA', 'Joshua Williams');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNMVOMD0IP848Q', 'New Stephanieville Branch', 'Chenshire', 'USA', 'Mrs. Amy Flores');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNFDSSN8DRYY8J', 'New Tracyhaven Branch', 'Pamelachester', 'USA', 'Krista Smith');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNZXMCSI9DVSQU', 'Leonmouth Branch', 'Hallbury', 'USA', 'Daniel Norris');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN44Y98LXMTKBN', 'Port Annamouth Branch', 'North Kevinburgh', 'USA', 'Renee Kelly');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNSZC55B1LNU4O', 'Kimberlyport Branch', 'New Michaelburgh', 'USA', 'Karen Nguyen');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNWTJ1BFQIZRIY', 'Gilbertstad Branch', 'West Katherine', 'USA', 'Rebecca Mitchell');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNOZXCFY1FLK6L', 'Blakeshire Branch', 'Lake Charlesville', 'USA', 'Barbara Alvarado');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN317DJ8SVBC99', 'Emilybury Branch', 'Clarkland', 'USA', 'Christopher Howard');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN6SFLI1YMWWA0', 'South Gary Branch', 'South Nicholaston', 'USA', 'Ashley Chen');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN16HA5GA5W3TM', 'East Mary Branch', 'Port Michellemouth', 'USA', 'Bryan Wolfe');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN1HTFXNO147XA', 'Christophertown Branch', 'North Kimberly', 'USA', 'Rhonda Colon');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNS0LY9P2T1N0C', 'Kerrbury Branch', 'North Pamelabury', 'USA', 'Dennis Burke');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN8KGOH1545S6Z', 'Kellyport Branch', 'Aliciaville', 'USA', 'Amanda Stewart');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNLUYQP6LK0USM', 'Johnview Branch', 'Cynthiaport', 'USA', 'Angela Colon');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNE1B035FD21QR', 'Port Christopher Branch', 'Leeside', 'USA', 'Jacob Short');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNIC2VG55LI3T3', 'New Linda Branch', 'Harrisstad', 'USA', 'Kevin Patel');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNSO0MY67DV9DB', 'East Christopherville Branch', 'Port Codychester', 'USA', 'Mr. Rodney Knight DDS');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN8RJWEE1G91J0', 'Lisaton Branch', 'West Kevin', 'USA', 'Sandra Castro');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNZ51FCUT9F0QS', 'East Williestad Branch', 'New Pamela', 'USA', 'Laura Nguyen');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNNP7BZ4OHTN21', 'South Francesview Branch', 'West Kevin', 'USA', 'Kathryn Cooper');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNO5UZ15B6TAS6', 'New Robert Branch', 'North Frankmouth', 'USA', 'Robin Rodriguez');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNW3FCQTCW9780', 'Mariaside Branch', 'Pinedabury', 'USA', 'Jason Moyer');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN4IGV7A8Z2SX2', 'Lake Brandiport Branch', 'Kellyton', 'USA', NULL);
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNIYUM6T0JBGQD', 'Lake Matthew Branch', 'Jacquelinemouth', 'USA', 'Johnny Wilson');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNZZ7ROHQUX000', 'Eddiefurt Branch', 'East Shelly', 'USA', 'James Olson');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNT4R9ZO68RXXF', 'West Robertmouth Branch', 'West Julietown', 'USA', 'Luis Bailey');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNIY0YKZWQQLIG', 'Christianborough Branch', 'Lake Davidborough', 'USA', 'Teresa Willis');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN5JDC1G0GIFVZ', 'Knightmouth Branch', 'Andreafort', 'USA', 'Mark Taylor');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN9OX9VFC4SL1S', 'Ginafort Branch', 'Lake Donna', 'USA', 'April Carpenter');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNGPK0FQCM19GR', 'West Jennifer Branch', 'New Brianfurt', 'USA', 'Joshua Hall');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNX2U9Y8UYXRBJ', 'Lake Nataliestad Branch', 'Coopershire', 'USA', 'Ms. Lisa Lawson');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNKCOL47K322JZ', 'New Michelleside Branch', 'Port Kimberlyfurt', 'USA', 'Janice Collins');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNHPQYW6CX2S2N', 'South Justinbury Branch', 'Perezfurt', 'USA', 'Lawrence Schultz');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNGTFV3W8RIWDX', 'Shahberg Branch', 'North Cindy', 'USA', 'Autumn Wells');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN2AP52401QFAS', 'Jonview Branch', 'Port Aaronshire', 'USA', 'Robin Weber');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNER2MAOZ1B097', 'Fisherview Branch', 'New Devinburgh', 'USA', NULL);
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNC0HF84LJZC6Z', 'West Andrew Branch', 'Freemanmouth', 'USA', 'Jessica Shaw');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNMQ04VIHI9S1B', 'Lake Tiffany Branch', 'West Timothybury', 'USA', 'Jonathan Davis');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNZ717CGXI1GB2', 'Andreafurt Branch', 'Mooreland', 'USA', 'Patrick Roberts');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN1529OT6NDJQ1', 'Shawnton Branch', 'Hortonhaven', 'USA', 'David Logan');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNCX8U4A5NX6JR', 'Johnsonstad Branch', 'Candaceside', 'USA', 'Heather Smith');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNEKAOVKDOA6XG', 'Gordonfurt Branch', 'East Williamfurt', 'USA', 'Amanda Singleton');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNY1ZQZN0UY2CK', 'Portermouth Branch', 'East Mariachester', 'USA', 'Shelly Davenport');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN9QEVXOZA7QR6', 'New Thomasstad Branch', 'South Jose', 'USA', 'Margaret Perez');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRND0NG8TVWBDJD', 'New Andreaborough Branch', 'Lake Robyn', 'USA', 'Matthew Carlson');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNUPPCXJ51PCXB', 'East Carolynshire Branch', 'Lake Michael', 'USA', 'Martin Coleman');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNGC6YE9MYY9MS', 'Kennethmouth Branch', 'Youngmouth', 'USA', 'Sheryl Baker');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNF4UQNXDFRRKE', 'Fowlerside Branch', 'New Jason', 'USA', 'Madison Watson');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNYH9EQFXVYZXP', 'Solismouth Branch', 'Dawsonfurt', 'USA', 'Paul Smith');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNKQNPRI6HECTB', 'Cobbfort Branch', 'South Joanna', 'USA', 'Steven Morgan');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNE30KB5D53EAP', 'Warrenview Branch', 'Lake Daniel', 'USA', 'Natasha Ramirez');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNL5W914LUO29H', 'North Michelle Branch', 'Ronaldborough', 'USA', 'Jamie Sanchez');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNB6ND74AYSFU3', 'Burkeburgh Branch', 'Cainmouth', 'USA', 'Dawn Shah');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN4F0W5E90CFP8', 'Lake Marktown Branch', 'Michaelbury', 'USA', 'Tim Christian');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNQSN78AWV0YAT', 'Lake Caitlyn Branch', 'Lopezton', 'USA', 'Michael Guerrero');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNXF7Q1OG0TJFK', 'Port Johnland Branch', 'Ericbury', 'USA', 'Jessica Yang');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN7FT429U437BF', 'Jordanmouth Branch', 'Aaronport', 'USA', 'Edwin Fleming');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNOAZ2BP3HXI6D', 'Brownland Branch', 'North Kristinamouth', 'USA', 'Rachel Delacruz');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN8T3CMEQPY8SZ', 'Dixontown Branch', 'Jacquelinehaven', 'USA', 'Brian Stanley');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNOK3FJ5QCHUF3', 'Keithbury Branch', 'South Jeremy', 'USA', 'Ronald Rios');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN0HGZM7VXCJIY', 'Edwardfurt Branch', 'Garciaside', 'USA', 'Melinda Chase');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNF17MU2UD3QZ2', 'Paulside Branch', 'Autumnmouth', 'USA', 'Theresa Ramos');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN0AXAWLCCL2AJ', 'West Stephen Branch', 'East Gregory', 'USA', 'Douglas Johnson');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN4OBKJ371M6U1', 'Mataville Branch', 'New Derrick', 'USA', 'Megan Anderson');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNBR76KBQGJ9JD', 'Emilyberg Branch', 'West Eileen', 'USA', 'Jose Glover');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNBGQO84HSG6T2', 'Arthurhaven Branch', 'East Lisa', 'USA', 'Amber Love');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN5ACYR8DQIEAM', 'East William Branch', 'Evansborough', 'USA', 'Elizabeth Serrano');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNCSRQ08U56ZRM', 'Hernandezport Branch', 'Adambury', 'USA', 'Shane Medina');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNEOHR1PV4LQ1G', 'Brendanstad Branch', 'North Nichole', 'USA', 'Jennifer Bennett');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNJRBT5GEK3IQ0', 'Warnershire Branch', 'Hooverside', 'USA', 'Sheila Hines');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNU7QLL3E1H86B', 'East Jenniferton Branch', 'Lake Danielfurt', 'USA', 'Gary Jackson');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNQDXOFL58YDX0', 'New Charlotteton Branch', 'Gutierrezberg', 'USA', NULL);
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNB6358PEGS1W8', 'Seanville Branch', 'Ericamouth', 'USA', 'Nicole Hancock');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNAK4EYBOSUC9C', 'Lauramouth Branch', 'Mariaborough', 'USA', 'Daniel Knight');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNN73V1Z7IJJFH', 'Smithland Branch', 'Millerstad', 'USA', 'Abigail Rosario');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNWPXLEEDM0VBI', 'East Edward Branch', 'Randallland', 'USA', 'John Castro');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNSDF2Q20IB6NR', 'Martinezchester Branch', 'Henrybury', 'USA', 'Caitlin Smith');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN9N2FLQEKMS5M', 'South Robin Branch', 'Erikchester', 'USA', 'Katie Miller');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN8NE7AIUA9KX8', 'North Kari Branch', 'Lake Kimberlyside', 'USA', 'Gregory Archer');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNY0M8DDR0ZGRO', 'East Ericfort Branch', 'Prestonborough', 'USA', 'Cynthia Briggs');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN7ZHHNR3QB9FT', 'West Brandon Branch', 'Hartchester', 'USA', 'Dawn Fletcher');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNXTST3JNLTA1Z', 'Nicholasland Branch', 'Port Sarah', 'USA', 'Patricia Young');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNMGLVS0D4VI18', 'Cynthiatown Branch', 'East Richard', 'USA', 'Chad Day');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNPDQKCULD0LVR', 'West Robert Branch', 'South Matthew', 'USA', 'Gabriella Joyce');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNJKCWHOBGAYP4', 'Tommymouth Branch', 'Pattonside', 'USA', 'Patricia Ramirez');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNGL8C2UZEM2MX', 'South Jonathantown Branch', 'Carrieshire', 'USA', NULL);
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNKIYHBSD9Y0SR', 'North Derrick Branch', 'Marshalltown', 'USA', 'Julia Wilson');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN13I7AM4HGBJD', 'South Juan Branch', 'Littleview', 'USA', 'Ashley Ho');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRND1VRLNBFQUGK', 'Lake Richard Branch', 'New Joseph', 'USA', 'Lauren Zimmerman');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN6LX6T6DKF4T5', 'Brittneyfurt Branch', 'Port Andrea', 'USA', 'Marie Jones');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNWUXNNRM7IYFW', 'Norrisberg Branch', 'East Markborough', 'USA', 'Katrina Baker');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN2IXRKXBCDF7I', 'West Paul Branch', 'Houstonmouth', 'USA', 'Michael Evans');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN3H235AZ3BRSV', 'Wattsville Branch', 'Stevenshire', 'USA', 'Kelsey Wright');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNZV3CNE3T4IRT', 'Jasmineburgh Branch', 'Lake Stephanieville', 'USA', 'Sherri Wood');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNB5TYJ13YMXT1', 'Gabriellehaven Branch', 'Andrewstad', 'USA', 'Matthew Collins');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNHV5X7B4VKMBS', 'Sparksville Branch', 'Port Teresa', 'USA', 'Andrea Morris');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN14PUEP1O2BCF', 'Gardnerbury Branch', 'East James', 'USA', 'Matthew Butler');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNSD457H84U6AL', 'West Ryanshire Branch', 'West Linda', 'USA', 'Aaron Pitts');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNQ05INPPA5QJ5', 'New Heidi Branch', 'Petersonbury', 'USA', 'Cole Bishop');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNYY2Y46YPCQQC', 'Amandaton Branch', 'Vargashaven', 'USA', 'Brian Peters');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNIT7WBRXFZNMF', 'Donaldstad Branch', 'Garciastad', 'USA', 'Destiny Guzman');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNH162HPE1HA56', 'Lake Stephenbury Branch', 'Rickyside', 'USA', 'William Frazier');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNOF0CW7KYTZAP', 'West Ashley Branch', 'North Ruth', 'USA', 'Damon Davidson');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNHRRMSZXNX1LB', 'Brownborough Branch', 'Feliciaton', 'USA', 'Dale Hall');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN9QD7VO63YXDO', 'Stephanieberg Branch', 'North Ashley', 'USA', 'Christina Garrett');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN97EB3C9EPN06', 'West Scottton Branch', 'Olivertown', 'USA', 'Joshua Johnson');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNJ77CLK7PFB4Z', 'East Timothy Branch', 'East Lorrainechester', 'USA', 'Jon Fitzgerald');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN36UAM8WDYAQ7', 'Maureenland Branch', 'Fordville', 'USA', 'Margaret Conway');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNYGFKBLY61HT9', 'New Charlene Branch', 'Lake Rachelview', 'USA', 'Evan Nunez');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN5G92OPJQ88UH', 'Ryanfort Branch', 'Stephenstown', 'USA', 'Tony Summers');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN3SIO63SNLU8B', 'Patricktown Branch', 'Wernerton', 'USA', 'Eric Murphy');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNYBC6K8D8HOAZ', 'Lake Kelseyview Branch', 'South Mollyton', 'USA', 'Michael Galloway');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN3E4VPX1TCC4Y', 'South Michael Branch', 'East Michele', 'USA', 'Wanda David');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN8LBNE4LXBYIW', 'New Danielchester Branch', 'Rossberg', 'USA', 'Melissa Frey');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN5HIW49P2BPH4', 'West Lindseychester Branch', 'Loganland', 'USA', 'Stuart Conrad');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN5C0YYHYKWOAQ', 'Derekfort Branch', 'South Lauren', 'USA', 'Christy Garcia');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN3A5JMS977Q7C', 'Davidton Branch', 'Lake Christopher', 'USA', 'William Cook');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNBYE5WPT7LOW4', 'North Zachary Branch', 'Sandersport', 'USA', 'Matthew Brown');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNZ9HQFJDPF152', 'Pearsonburgh Branch', 'East Kelly', 'USA', 'Cathy Parker');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNMVI493CU471F', 'South Amber Branch', 'Williamsshire', 'USA', 'Jason Stevens');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNZYSXB1UYNU2E', 'Williamston Branch', 'Danielchester', 'USA', 'Sandra Bryant');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNDTZX3KR3GQ1M', 'Lake Raymond Branch', 'South Helen', 'USA', 'Donna Gonzales');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN8BHXJE97NAS7', 'East Trevorland Branch', 'New Lauratown', 'USA', 'Julie Oneal');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNFEMYQL9UYUZZ', 'West Jeffrey Branch', 'Yatesshire', 'USA', 'Juan Drake');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNGOHDMK9LYGHQ', 'Port Marissa Branch', 'Cindyshire', 'USA', 'John Turner');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNWZWECWWPATJE', 'North Lisamouth Branch', 'Paulaborough', 'USA', 'Deborah Hart');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNO260O6I051HB', 'South Danielhaven Branch', 'North Meganton', 'USA', 'Jennifer James');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNZSPSOZ6LODXP', 'South Stephenside Branch', 'Christopherchester', 'USA', 'Dr. Derrick Meza DDS');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNT57K56CHGAJ3', 'Lake John Branch', 'Meyerstad', 'USA', 'Michael Winters');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNJUGEBKM73NKP', 'Dickersonstad Branch', 'Lake Charles', 'USA', NULL);
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNBDFE4M3PORPR', 'Lake Shawnburgh Branch', 'Sarahborough', 'USA', 'Wendy Ramirez');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNCF2SY142LO5G', 'Malloryborough Branch', 'North Kristina', 'USA', 'Richard Henderson');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNECXDTKFRKVTN', 'Port Christopher Branch', 'Barnettview', 'USA', 'Anna Miller');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN3SCXNYUGC86Q', 'Callahantown Branch', 'Port Josephmouth', 'USA', 'William Lyons');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN7EJEIQ3M0OKZ', 'South Phyllis Branch', 'Matthewston', 'USA', 'Brittany Butler');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNVSB0T7FPRJ2X', 'New Gregory Branch', 'Jordanview', 'USA', 'Donna Hughes');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNQ3ALA2TCFHGO', 'Ruizside Branch', 'Port Christina', 'USA', 'Debra Foster DVM');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN9HHG8LK37M66', 'Craigland Branch', 'Masonbury', 'USA', 'Robert Prince');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN7DZQM1QLBKXA', 'Lake Shannonbury Branch', 'East Mark', 'USA', 'John Lewis');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNKNZFFTXN3YZV', 'Lake Ryan Branch', 'South Joyce', 'USA', 'Tracy Knapp');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN44W96D0K04MN', 'Lake Elijah Branch', 'New Anne', 'USA', 'Diana Erickson');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN05AOR2C7I0FZ', 'Allenmouth Branch', 'West Miranda', 'USA', 'James Mejia');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN9O4KPX513GXG', 'Jessicashire Branch', 'Millerfort', 'USA', 'Mary Knight');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN43EIZ4QLVG3K', 'New Brianville Branch', 'Tammyton', 'USA', 'Jerry Miller');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNGNQKGH43T32B', 'Helenfurt Branch', 'Maldonadomouth', 'USA', 'Jordan Harris');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNPWX8L7WHK86T', 'Ruthville Branch', 'Ashleyborough', 'USA', 'Michael Pacheco');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNNDSYVIKRWCZG', 'Jamesmouth Branch', 'West James', 'USA', 'Mr. Gregory Evans');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNHVF0HB8I1LGJ', 'Dawnton Branch', 'Novakshire', 'USA', 'Samantha Owen');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNGU3VL3ZV2EYS', 'North Shannonberg Branch', 'Michaelshire', 'USA', 'Julie Steele');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNJXUPZ022PYK7', 'Lake Angelaton Branch', 'Colleentown', 'USA', NULL);
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNQ7WBARWBZ2PR', 'East Patriciafurt Branch', 'Juliaport', 'USA', 'Adam Brown');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN1LHM3HYVOMFS', 'New Georgebury Branch', 'Ryanborough', 'USA', 'Terry Wilson');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNJHH3HUUTIQO5', 'East Charles Branch', 'New Amy', 'USA', 'Jamie Curtis');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNIWXEDEKZ45EA', 'Barbaramouth Branch', 'South Cindyview', 'USA', 'Kayla Williamson');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNDSHI3CGXFCQP', 'Kevinshire Branch', 'Lake Lisaville', 'USA', 'Jenna Lawson');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN3WT7I1XFYQAZ', 'Port Jenniferland Branch', 'Powellburgh', 'USA', 'Kyle Wilson');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN9KFF8054EG3S', 'New Charles Branch', 'New Noah', 'USA', 'Austin Church');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNTNNN1P2B2G7O', 'Port Claudiachester Branch', 'New Pamela', 'USA', 'Chad Howard');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNUPZAT6FGDX4I', 'North Ashleystad Branch', 'East Jamiemouth', 'USA', 'Tina Mitchell');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNUC2W69OL6HRF', 'Port Kimberly Branch', 'South Joseph', 'USA', 'Nathan Hernandez');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN936E6Q92GNMF', 'Lake Lauraside Branch', 'Sandraview', 'USA', 'Connor Walker');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNBROAHK2TN2T0', 'Port Dylan Branch', 'Alexandershire', 'USA', 'Elizabeth Weiss');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNB9IL40JGSYKF', 'New Ashley Branch', 'East Ericberg', 'USA', NULL);
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN6QEI97XYVQRZ', 'Kramerhaven Branch', 'Lake John', 'USA', 'Kimberly Page');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN57YRLZ0KAAF2', 'Davisville Branch', 'North Timothy', 'USA', 'April Torres');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNHIHWK8ZA3MLM', 'Port Christopherbury Branch', 'Reneefurt', 'USA', 'Miss Emily Henson');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN2RVDNXAESQOH', 'Steelechester Branch', 'Sawyerberg', 'USA', 'Jenny Conley');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNSB91F9M6KFQ4', 'West Latoya Branch', 'Thomasville', 'USA', 'Grace Cooper');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNI3840XVQM7YY', 'Mosleyton Branch', 'Smithfurt', 'USA', 'Courtney Nguyen');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN01QV7ZIPBX20', 'Karenland Branch', 'West Jenniferhaven', 'USA', 'David Vaughn');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN9X4NKEOBBV8J', 'Paulton Branch', 'Shawnport', 'USA', 'Mr. James Harding MD');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNGDQ4NQSM3F4F', 'New Thomasside Branch', 'North Juan', 'USA', 'Michael Fox');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN30IZXHLPVFKJ', 'Sheilaville Branch', 'Lake Marcus', 'USA', 'Adam Trujillo');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNL2GFILHU2JZV', 'Charlesland Branch', 'Lake Rosestad', 'USA', 'Kevin Young');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNAAHBXLM0C5RU', 'Churchburgh Branch', 'Adriennetown', 'USA', 'Sarah Buchanan');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNO8K2P8C7B31N', 'Allenmouth Branch', 'Huntbury', 'USA', 'Alyssa Harding');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN7HDLCKEGFBT7', 'Tanyachester Branch', 'Mariaville', 'USA', 'William Klein');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNWQC6B0O5MRYY', 'New Denisestad Branch', 'East Bridgetton', 'USA', 'Robert Phillips');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNGGMHSW4EW90K', 'Steventon Branch', 'West Tracytown', 'USA', 'Kristin Lang');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNBBNMJBMB9UCX', 'Port Lauraborough Branch', 'Leslieton', 'USA', 'Stacy Lewis');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNQKANSZNO5NGN', 'Kennethfort Branch', 'Bellfort', 'USA', 'Jacqueline Alexander');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN0B6Q3BZTNP6R', 'Myersburgh Branch', 'Antonioland', 'USA', 'Dale Escobar');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNH8LP2TVXAYZ7', 'North Michaelberg Branch', 'Abigailville', 'USA', 'Craig Ray');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNJM43XGQ24X60', 'Schmidtmouth Branch', 'Santanahaven', 'USA', 'Michelle Johnson');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNW6OM4FWN8ZIM', 'South Troy Branch', 'Dianeland', 'USA', 'Cynthia Bennett');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNJQKE6O22Z37Q', 'Jeanetteport Branch', 'Travisbury', 'USA', 'Thomas Austin');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNB1X3IH8K9SRR', 'East Nicholasville Branch', 'North Monica', 'USA', 'Charlene Grimes');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNKA5V67WDEI98', 'Hammondberg Branch', 'New William', 'USA', 'Christopher Shaw');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNMU36MTL9AYDL', 'Kimside Branch', 'East Nathanberg', 'USA', NULL);
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN5K43WTAL2IPJ', 'Charlesborough Branch', 'South Cassandra', 'USA', 'Antonio Martin');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNE7BELGO2N4L6', 'Cynthiashire Branch', 'Grimesshire', 'USA', 'Matthew Hill');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNJEFF7GDCV9D8', 'North Heatherfort Branch', 'Haleytown', 'USA', 'Kristina Carter');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNBSS9THQ1F34T', 'Michaelborough Branch', 'Castroshire', 'USA', 'Sean Edwards');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNILID3QWGTQ0B', 'East Joanna Branch', 'South Victoria', 'USA', 'Adam Jones');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNHTZJT8BHZIJY', 'Donaldview Branch', 'North Kellyfort', 'USA', 'Cody Gutierrez');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNXTWSEMDF7NBU', 'Lake Susanfort Branch', 'South Teresabury', 'USA', 'Alyssa Diaz');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN4LGL9X23OEIW', 'Martinville Branch', 'Port Chelsealand', 'USA', 'Charles Nelson');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN6MRNKHAEXKA9', 'Port George Branch', 'Fergusonview', 'USA', 'Alexander Clark MD');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNVMPFOS2POLPG', 'Huynhport Branch', 'Lake Joshuabury', 'USA', 'Mr. David Andersen PhD');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNX1QNK9WDY13I', 'Lake Sethbury Branch', 'Salinasland', 'USA', 'Lindsey Vance');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN7WNJ2W77O1ZP', 'Port Leahside Branch', 'Johnsonbury', 'USA', 'Alexandria Parker');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNOQLK1OJ7YRJC', 'Cameronberg Branch', 'Sandraport', 'USA', 'Helen Peters');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNHN2FDF6LY5AZ', 'East Charles Branch', 'Smithfurt', 'USA', 'Matthew Ramirez II');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNHWD2PZ4USW0P', 'West Dannyborough Branch', 'Amandatown', 'USA', 'Maurice Mitchell');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNRO9F5LEUFWI5', 'Smithtown Branch', 'Taraville', 'USA', 'Jason Boyle');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNK921WI34LC9I', 'North Sara Branch', 'East Laurahaven', 'USA', 'Michelle Russell');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN3KPXM7H88W2B', 'Roseburgh Branch', 'Pierceport', 'USA', 'Misty Parker');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN88JGHLNMQGPD', 'Ramirezport Branch', 'Alejandroside', 'USA', 'Taylor Peters');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNJ71YZLCO103U', 'South Williamborough Branch', 'West Jimmyton', 'USA', 'Kendra Mcintosh');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNUJNRRWD3ZF1U', 'Port Luis Branch', 'West Lindachester', 'USA', 'Jeffrey Duncan');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNE6N0Y7OAWG0Q', 'Dennisside Branch', 'Jamesview', 'USA', 'Nicole Hernandez');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNJE8I6P7XRIVP', 'Maxland Branch', 'Hannahton', 'USA', 'Megan Smith PhD');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNZHDX0G531SCU', 'Lake Arielland Branch', 'Lake Timothy', 'USA', 'Kyle Vazquez');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN05OCMRJWXO3A', 'Sharonstad Branch', 'Port Kelly', 'USA', 'Roger Peterson');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNZVXX7XHOGZ1K', 'West Gina Branch', 'West Marvinstad', 'USA', 'Christopher Dudley');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN4ETNXPNRUX4X', 'Port Jennifer Branch', 'Goldenmouth', 'USA', 'Christopher Murray');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNPGDKFNLAM6CA', 'Powellchester Branch', 'Johnside', 'USA', 'Daniel Moreno');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNWSOJ5UHKR647', 'Burgessfort Branch', 'Lowefurt', 'USA', 'Dr. Adam Wright III');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNRQ2ZF66JVUDF', 'Barbaramouth Branch', 'South Casey', 'USA', 'Elizabeth Nelson');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNCKY7UJOQAD3J', 'Lake Carl Branch', 'Deborahville', 'USA', 'Robert Floyd');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNEBNYD36KEDG8', 'North Jennifermouth Branch', 'Quinnfurt', 'USA', 'Denise Jacobson');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN0EBT75533V2K', 'Lake Jerome Branch', 'East Julieberg', 'USA', 'Joshua Gomez');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN90LCGHKCNRGF', 'Port Peterberg Branch', 'Whiteshire', 'USA', 'Stephen Sanders');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNYYF29TC9NGKN', 'Miguelhaven Branch', 'North Bailey', 'USA', 'Michael Guzman');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNNR9S9MUSXWXC', 'North Susanville Branch', 'South Justinside', 'USA', 'Matthew Rogers');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN8VKLJ0TJMNH6', 'Taylorburgh Branch', 'Lewistown', 'USA', 'Wendy Winters');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNKOBV6R8WNTNC', 'West Jacqueline Branch', 'Port Phyllis', 'USA', 'Mrs. Kayla Nixon');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNYGBLGM2XLV5L', 'Jimenezside Branch', 'North Ricardo', 'USA', 'Samantha Sandoval');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN18IE9AYSH0YY', 'Debbietown Branch', 'New Robert', 'USA', 'Emma Morris');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNKPR9SRK27A19', 'Mitchellview Branch', 'West Jennifer', 'USA', 'Valerie Welch');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNF2059Z6LAF0Q', 'Lake Brian Branch', 'Scottton', 'USA', 'Travis Miller');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNEJJIPKB0TIBG', 'South Leahside Branch', 'North Dillonside', 'USA', 'Katherine Rivera');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN4CKQND0YF5YL', 'South Jefferyfort Branch', 'Stanleyside', 'USA', 'Jennifer Lopez');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNVQGQYWDCRTU4', 'Shannonton Branch', 'North Nathan', 'USA', 'Edward Barnes');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNIYBL4MUFQ12B', 'Port William Branch', 'Lake Timothy', 'USA', 'Dean Reid');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNC8M41KLUW3SP', 'Port Melanieberg Branch', 'Port Kevin', 'USA', 'Michael Richardson');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNEK7CWEH694W7', 'Kristaport Branch', 'Port Karitown', 'USA', 'Daniel Crawford');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNCEKQP3M6N8EA', 'Leahhaven Branch', 'Rebeccaberg', 'USA', 'Shelby Sheppard');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN01VTGFV371N5', 'East Timothyton Branch', 'Alexanderfort', 'USA', 'David Martinez');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNINE5R0FTKRYJ', 'Lindsaymouth Branch', 'North Williamfurt', 'USA', 'Kathryn Copeland');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNZZQBVC5DOQ48', 'Annberg Branch', 'New Vincentside', 'USA', 'Grace Williams');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN0GWM7RW000YS', 'North Keithshire Branch', 'New Ashley', 'USA', 'Desiree Smith');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNE0W7RKXYFF7E', 'Bairdfurt Branch', 'East Roberttown', 'USA', 'Brittney Bowen');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNRNH88JB46D4K', 'Douglasfurt Branch', 'Port Jasonbury', 'USA', 'Eddie Martinez');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN3A4GJB8LRFEA', 'Valdezside Branch', 'Anthonyview', 'USA', 'James Brown');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNKF1FR3KQPDZ5', 'Lake Natashaborough Branch', 'Lake Thomas', 'USA', 'Priscilla Wallace');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNCKWWRD915JDD', 'Port Mary Branch', 'New Kathryn', 'USA', 'Dennis Anderson');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNE5S8D4QB4G46', 'South Tommyside Branch', 'Amyshire', 'USA', 'Robert Mahoney');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNQYW3620MT69Z', 'New Danielburgh Branch', 'Rodneyside', 'USA', 'Victor Moyer');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRND2Q51GSK3LSK', 'Harringtonfurt Branch', 'Smithtown', 'USA', 'James Williams');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN6RC038Q7F5K6', 'West Richardchester Branch', 'South Garrett', 'USA', 'Madison Gomez');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNVQ3SWCRZ49B3', 'Janetmouth Branch', 'Kruegertown', 'USA', 'Jennifer Garcia');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNCRSBV9HAZL90', 'Lake Joshuachester Branch', 'Meganville', 'USA', 'Joseph Montgomery');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNMPUQCHDP6BA9', 'Jamesfurt Branch', 'Port Barbara', 'USA', 'Katie Wang');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNDXUZ4EC70TWE', 'Gibsonborough Branch', 'North Scott', 'USA', 'Janet Sanders');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN2M5N3OHATCE3', 'Parkchester Branch', 'North Michelle', 'USA', 'Ashley Potts');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNYAM3ZFBYMBDB', 'Erinside Branch', 'Calebberg', 'USA', 'Mrs. Stephanie White');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNGI846NTEYLC0', 'Lake Austin Branch', 'Martinton', 'USA', 'Walter Martinez');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNI60LMMX7RO34', 'East Patrickstad Branch', 'Jacksonhaven', 'USA', 'Steven Jennings');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNFX6YY5EVC00X', 'West Paulashire Branch', 'South Thomasborough', 'USA', 'Steven Forbes');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNYRA9YTCL61ZK', 'Scottside Branch', 'North Josephbury', 'USA', 'Christopher Bowman');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNQD9QX7SW4GVJ', 'South Amanda Branch', 'East Denise', 'USA', 'Jonathan Mendez');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNNF1BCHW43NLJ', 'Port James Branch', 'Russellchester', 'USA', 'Tracy Bailey');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN1QT1AY9WSZFW', 'West Ryan Branch', 'Michaelborough', 'USA', 'Timothy Lamb');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNZ5WHUU00QSTR', 'Benjaminborough Branch', 'West Markton', 'USA', 'Lucas Walker');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNCTSUNOJEPGOX', 'Brownbury Branch', 'Lake Josephbury', 'USA', 'Carla Joyce');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNIO82FS9WF2FM', 'North Amandatown Branch', 'Kramerfurt', 'USA', 'Dr. Dustin Bowers MD');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNIAYADX281ELB', 'Port Heather Branch', 'Thompsonberg', 'USA', 'Jill Castillo');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNDCATCG5APL5Q', 'West Samantha Branch', 'East Tammychester', 'USA', 'Timothy Gomez');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNGM0HE1BA7BHR', 'North Jorgeport Branch', 'Teresaborough', 'USA', NULL);
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNJ5NLG3N0HCDD', 'New Suzanne Branch', 'North Krystal', 'USA', 'Daniel Shea');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNUAHO1OSDGATR', 'Garciabury Branch', 'New Bethanyborough', 'USA', 'Victoria Perez');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNJ96XVEJ1Y5I0', 'Lake Monique Branch', 'Lewismouth', 'USA', 'Eric Mcdowell');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN40TCEQA4TBYD', 'Bowenport Branch', 'West Kimside', 'USA', 'Daniel Schroeder');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNGLW65F8V3ZVG', 'Michelleport Branch', 'Robertberg', 'USA', 'Melissa Mitchell');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN1SNV33A48L7K', 'Vazquezview Branch', 'New Stacyview', 'USA', 'Kevin Malone');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNL2DBPXZ0WI4Y', 'Leonstad Branch', 'Johnsonland', 'USA', 'Kathleen Lopez');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNS4A2Q24O50A5', 'Michaelton Branch', 'Jamesstad', 'USA', 'Lauren Rodriguez');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNBR1K8VKJL1LL', 'South Kristin Branch', 'Port Rebeccashire', 'USA', 'Anthony Fisher');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNZXSZI6MW56CY', 'East Amychester Branch', 'Hansenberg', 'USA', 'Jacob Schmidt');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNQFWHLKBB610I', 'Williamfurt Branch', 'West Johnfurt', 'USA', 'Andrew Martin');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN6V6F97R08V03', 'Wallaceton Branch', 'Ginaland', 'USA', 'Paul Reed');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNEFZ62VL8TQTG', 'East Nicoleland Branch', 'Beckerton', 'USA', 'Elizabeth Henderson');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNXOY3DSFKCGXR', 'North Jessica Branch', 'Kariborough', 'USA', NULL);
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNRYSFXT625E5A', 'East Victortown Branch', 'Perryfort', 'USA', 'Perry Woods');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNHDTYH2OXIDBT', 'Camachomouth Branch', 'Laurashire', 'USA', 'Colleen Kent');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNMX3YPPA70LE6', 'Jonathanland Branch', 'Phillipston', 'USA', 'Sarah Hernandez');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNIU2Z66PVIMJ5', 'North Sarah Branch', 'Reynoldstown', 'USA', 'Donna Hayden');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN1QXLPFN8LU9T', 'Susanmouth Branch', 'Wilkinsside', 'USA', 'Christine Ramirez');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN6LPK25MWQKKA', 'Valeriechester Branch', 'Shawnview', 'USA', 'Christina Sparks');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNC23ZQR3T96V0', 'Lake Joseph Branch', 'Ryanstad', 'USA', 'Joshua Davis');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN3YTZJVG7QBGF', 'Margaretland Branch', 'Powerston', 'USA', 'Mr. Devon Nelson');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNUQA8GAY8QEEP', 'Lake Luiston Branch', 'East Ashley', 'USA', 'Holly Juarez');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNUA1ILL9RXLYP', 'South Jessica Branch', 'Romeroville', 'USA', 'Margaret Duncan');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN2O44XWF2G3CR', 'Kellyview Branch', 'Elizabethview', 'USA', 'Sarah Taylor');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN8K2OZKDBQZU2', 'South Angelaland Branch', 'Johnberg', 'USA', 'Kenneth Holland');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN8GHHHKWH8JNZ', 'Davisville Branch', 'Harveychester', 'USA', 'Michael Sanders');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNYKWYW2YLW0NU', 'Port Jeffrey Branch', 'Velazquezberg', 'USA', 'Ronald Thomas');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN7J0AF3UML1ID', 'Aaronborough Branch', 'Cynthiahaven', 'USA', NULL);
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN31OM3XCW23ES', 'New Alison Branch', 'Millsville', 'USA', 'Martha Parker');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNB1M4RC1R200H', 'Port Bonniefort Branch', 'South Brian', 'USA', 'Christina Shaw');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNY67JCGP6U29Y', 'Lake Phillipborough Branch', 'Sosashire', 'USA', 'Timothy Short');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN3KGXQLLSZ1B2', 'Jacobview Branch', 'Lisaberg', 'USA', 'Nicole Smith');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN4GAMZZFYJB1E', 'Pricestad Branch', 'Cummingsborough', 'USA', 'Olivia Williams');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNTX5BV4JG9VY7', 'Lake Dale Branch', 'South Andrewfort', 'USA', 'Monica Mueller');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNFUJ36OMYFMU3', 'Lake Sherriberg Branch', 'South Michelle', 'USA', 'Amy Armstrong');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNO5M8ZSZRIF7B', 'Longside Branch', 'Marieview', 'USA', 'Erin White');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNIISN3S1JILZS', 'Maryshire Branch', 'Muellerport', 'USA', 'Jamie Mckee');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN37HBVQFCXMP7', 'Jimview Branch', 'West Mark', 'USA', 'Mrs. Sheila Estrada DDS');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNN5OBYS3A3T8V', 'Matthewville Branch', 'Lake Chadfort', 'USA', 'Miss Andrea Williams');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNW50D7NU43X89', 'Christopherbury Branch', 'Deniseview', 'USA', 'Melanie Flores');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNSV6L5FSFVUG0', 'West Jesuschester Branch', 'Robinsonland', 'USA', 'Joseph Haynes');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNQZ3H601N2YY1', 'South Caleb Branch', 'Johnnyton', 'USA', 'Elijah Miller');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNCJRW3GCRUJCB', 'New Colinland Branch', 'East Lindsey', 'USA', 'Robert Ferguson');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNI3ZZT3QI4RA8', 'Desireeton Branch', 'New Megan', 'USA', 'Emily Peterson');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNAOPG1TRE0URM', 'Lisamouth Branch', 'Floydview', 'USA', 'Sharon Bailey');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNV8JPWQT2EZ15', 'South Anthony Branch', 'Port Cindyport', 'USA', 'Ryan Patterson');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN63KL3O45J4P7', 'Levinetown Branch', 'West William', 'USA', 'Kevin Wright');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNFZKZIP4G7182', 'Seanville Branch', 'South Brian', 'USA', 'Austin Conley');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNE6ZIHLONJ5TA', 'North Patrickstad Branch', 'New Meaganchester', 'USA', 'Margaret Macdonald');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNUT9KROAID8MR', 'Port Carlborough Branch', 'Smithtown', 'USA', 'Nicholas Ramos');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN49HYVG7N1HHJ', 'Schneiderton Branch', 'Amandaville', 'USA', 'Tammy Bailey');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRND0PKNTYY7XOV', 'Scottport Branch', 'Port Virginiabury', 'USA', 'Melissa White');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNIU4ZR7URVE0J', 'Amyside Branch', 'Christinaport', 'USA', 'Michael Christensen');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNR7RU2ME22VDD', 'East Jamieborough Branch', 'Port Terri', 'USA', 'Casey Mann');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN67C5BWVWJ670', 'North Jamesside Branch', 'South Richardfurt', 'USA', 'Wendy Kirk');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN2X89QBSGFVCF', 'Port Davidbury Branch', 'Port Catherine', 'USA', 'Justin Murray');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNYOKCSQPBTJIF', 'Johnstad Branch', 'Kiddberg', 'USA', 'Patrick Torres');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN1F9F6WTY41OZ', 'Lindaland Branch', 'South Brianland', 'USA', 'Holly Gutierrez');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNALN0C3S5O8NQ', 'Scottville Branch', 'East Eric', 'USA', 'James Andrews');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNRZLNDOPYAMJ5', 'East Valerie Branch', 'South Justinstad', 'USA', 'Dalton Coleman');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN1GZPFAQ4IEMG', 'East Brianbury Branch', 'Carsonbury', 'USA', 'Janet Murphy');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNLZTFI3XBP95F', 'Port Gabriellashire Branch', 'Lake Jeffrey', 'USA', 'Jonathan Brown');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNYJH0HBYZESSI', 'Amyport Branch', 'Carterhaven', 'USA', 'Emily Smith');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNJUFNI17I606B', 'Richardfurt Branch', 'North David', 'USA', 'Ryan Sanchez');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN3BWFMSTOU2DJ', 'Gonzalezville Branch', 'North Brandonview', 'USA', 'Rebecca Townsend');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN2U6Y5LJWFAYW', 'East Marcus Branch', 'Aaronside', 'USA', 'Joshua Rasmussen');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN4KN4G14R482S', 'North Janetside Branch', 'Lake Gabrielstad', 'USA', NULL);
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN9OQFT9AJ25VE', 'Brettbury Branch', 'West Stephaniefort', 'USA', 'Denise Hill');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNV0Z4C9S1I8IR', 'Michellestad Branch', 'New Francis', 'USA', 'Anthony Todd');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN1PUQTK02DMWL', 'Millershire Branch', 'Tonyaview', 'USA', 'Jason Bowman');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNE02HGMX6YBD4', 'Jamesfort Branch', 'South Karen', 'USA', 'Joshua Gonzales');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN9OEHGR43U3XM', 'Jimmyborough Branch', 'Shawnborough', 'USA', 'Christian Olson');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNW4EOSLLX3ZNS', 'Tamaramouth Branch', 'East Dana', 'USA', 'Carlos Jenkins');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNTXFN44QQ05MN', 'South Michaelland Branch', 'New Carolynburgh', 'USA', 'Dr. Anthony Moss PhD');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN0LVJ9QUGCBXQ', 'Lake Ericstad Branch', 'Port Christian', 'USA', 'Anthony Lindsey');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNRAHZNRCGQV8N', 'Donovanport Branch', 'Sarachester', 'USA', 'Michael Roy');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNY5YTP7267FFD', 'Whitneytown Branch', 'Lake Coryside', 'USA', 'Kelli Brady');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN50VOS7MFZ3H4', 'Yesenialand Branch', 'Robertsville', 'USA', 'Susan Chandler');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNAPDMGBQ9TZ2J', 'Pattersonborough Branch', 'Jasonchester', 'USA', 'Jonathan Kent');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN8F6WKI9ZYCV6', 'North Evanhaven Branch', 'New Wendy', 'USA', 'Tammy Gonzalez');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNGMUSEWR3OSAF', 'East Jessicamouth Branch', 'North Jillton', 'USA', 'Ryan Holmes');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNAL4BAPG41XUQ', 'New Seanborough Branch', 'Lake Davidmouth', 'USA', 'Vickie Berg');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN3J3QMAGYVOG2', 'East Luke Branch', 'Lake Jennifer', 'USA', 'Daniel Bass');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN4AC2ZWED8KHP', 'Padillastad Branch', 'Hunterton', 'USA', 'Valerie Butler');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNEGTI1E1BUPAM', 'Lauraport Branch', 'Port Matthew', 'USA', 'John Romero');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNKWKU6JTDF2P9', 'Mendozamouth Branch', 'Port Bailey', 'USA', 'Denise Robinson');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNKAVKLFOVZG2N', 'New Lori Branch', 'Bryanthaven', 'USA', 'Sonya Jacobs');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNO9F0PIOAZ0ZN', 'Lake Veronicatown Branch', 'Guzmanville', 'USA', 'Mary Dunlap');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNEP10CRYO1PR5', 'Mathisberg Branch', 'South Clayton', 'USA', 'Kyle Green');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN7UD2E5GTGETB', 'Port Mary Branch', 'Joneschester', 'USA', 'Jared Lawrence');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNWAN821CBQTLI', 'Wilkinsborough Branch', 'Cooleyfurt', 'USA', 'Larry Williams');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNSK0HA6XDXNPL', 'Lake Nicole Branch', 'Brownburgh', 'USA', 'Michael Daugherty');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN54T0MZ660HFQ', 'North Cory Branch', 'West Peterfurt', 'USA', 'Rose Guerrero');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN2S3GN5AWG9LZ', 'West Kellyborough Branch', 'South Jaredville', 'USA', 'Robert Curtis');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNIB84YI4L5Y8W', 'Lake Christopher Branch', 'Tapiamouth', 'USA', 'Nancy Higgins');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNUJ8UKPOH8WYP', 'Robersonport Branch', 'Larryview', 'USA', 'Luis Shields');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNJFPW26GGKBS4', 'South Leonardview Branch', 'Matthewborough', 'USA', 'Rebecca Mahoney');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNRKXR6D2ZSGZ1', 'West Nataliehaven Branch', 'North Saramouth', 'USA', 'Craig Washington');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNSR9F7HU9SDWC', 'East Melanie Branch', 'West Jenniferchester', 'USA', 'Yolanda Hahn');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNA0XIEKTWQSG8', 'South Danielshire Branch', 'Marybury', 'USA', 'Kathleen Ortiz');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRN43D0G4WY9QMT', 'Williamsview Branch', 'New Tracy', 'USA', 'Breanna Sutton');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNF3AGQ3KDYKHH', 'Port Marcus Branch', 'New Josephport', 'USA', 'Katrina Miller');
INSERT INTO branches (branch_id, branch_name, city, country, manager_name) VALUES ('BRNWQLP45Y0KI7U', 'South Traceymouth Branch', 'East Samanthamouth', 'USA', 'Blake Flynn');
